name = "kaigo-quiz-api"
main = "worker.js"
compatibility_date = "2026-05-16"

[[d1_databases]]
binding = "DB"
database_name = "kaigo-quiz-db"
database_id = "016e7c-87a8-4048-9685-87830386c307"

[[r2_buckets]]
binding = "QUIZ_IMAGES"
bucket_name = "kaigo-quiz-images"

[vars]
R2_PUBLIC_BASE_URL = "https://pub-40d1fba7f9264555aa707424f181fde5.r2.dev"
